# Generated by Django 5.0.7 on 2024-07-17 17:18

from django.db import migrations

def create_data(apps, schema_editor):
    Blog = apps.get_model('blogs', 'Blog')
    Blog(title="Technology Blog", article="topnotch technologies to create react app...", author="sanchita", created_date="").save()

class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
