# Generated by Django 5.0.7 on 2024-07-19 15:10

from django.db import migrations

def create_data(apps, schema_editor):
    Blog = apps.get_model('blogs', 'Blog')
    Blog(title="Technology Blog", article="Acticles on topnotch tech....", author="Sanchita").save()

class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(create_data),
    ]
